export enum RuleType {
    Swap = 'swap',
    Letters = 'letters',
    Prefix = 'prefix',
    Suffix = 'suffix',
    WordPrefix = 'wordPrefix',
    WordSuffix = 'wordSuffix',
    Custom = 'custom',
    Charset = 'charset',
    Lookaround = 'lookAround',
    Bold = 'bold',
    Italic= 'italic',
    BoltItalic = 'boltItalic',
    Underline = 'underline',
    Strikethrough = 'strikethrough',
    Code = 'code',
    Spoiler = 'spoiler',
    Quote = 'quote',
    Sub = 'sub',
    Super = 'super',
}