export enum RuleType {
    Swap = 'swap',
    Letters = 'letters',
    Prefix = 'prefix',
    Suffix = 'suffix',
    Wrap = 'wrap',
    Censor = 'censor',
    Stutter = 'stutter',
    Custom = 'custom',
    Repeat = 'repeat',
    Charset = 'charset',
    Capture = 'capture',
    Lookaround = 'lookaround',
    Case = 'case',
    Reverse = 'reverse',
    Hashtag = 'hashtag',
    Boundary = 'boundary',
    Symbol = 'symbol',
    SplitJoin = 'splitjoin',
    Markdown = 'markdown',
    Zalgo = 'zalgo',
}