export enum RuleType {
    Swap = 'swap',
    Letters = 'letters',
    Prefix = 'prefix',
    Suffix = 'suffix',
    WordPrefix = 'wordPrefix',
    WordSuffix = 'wordSuffix',
    Custom = 'custom',
    Repeat = 'repeat',
    Charset = 'charset',
    Lookaround = 'lookAround',
    Case = 'case',
    Reverse = 'reverse',
    Boundary = 'boundary',
    Symbol = 'symbol',
    SplitJoin = 'splitJoin',
    Markdown = 'markdown',
}